In [47]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [59]:
df = pd.read_csv("SPECT.csv")
df.head()

,Class,Attr_1,Attr_2,Attr_3,Attr_4,Attr_5,Attr_6,Attr_7,Attr_8,Attr_9,...,Attr_13,Attr_14,Attr_15,Attr_16,Attr_17,Attr_18,Attr_19,Attr_20,Attr_21,Attr_22
0,1,0,0,0,1,0,0,0,1,1,...,1,1,0,0,0,0,0,0,0,0
1,1,0,0,1,1,0,0,0,1,1,...,1,1,0,0,0,0,0,0,0,1
2,1,1,0,1,0,1,0,0,1,0,...,1,0,0,0,0,0,0,0,0,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,1
4,1,0,0,0,0,0,0,0,1,0,...,1,0,1,1,0,0,0,0,0,0

In [63]:
def kfold(df,n):
    part = 1.00/n
    cur = part
    for i in range(n):
        df = df.sample(frac=1)
#         train_y = df['Class'][part:]
#         features = df
#         features.drop('Class',axis = 1,inplace = True)
#         train_x = features[part:]
#         test_y = df['Class'][:part]
#         test_x = features[:part]
        train, test = train_test_split(df, test_size=part)
        part = part + cur
        k= 5
        out = knn(k,train,test)

In [81]:
def knn(k,train,test):
    prediction = []
    for t in test.iterrows():
        dist= []
        for row in train.iterrows():
            s = 0
            for g in range(2,len(row)):
                s += (t[g]-row[g])**2
        dist.append([row[1],s])
        print(dist)
        arr = sorted(dist,key= lambda x: x[1])
        arr = arr[:k]
        pos,neg = 0,0
        
        for i in arr:
            if i[0]==1:
                pos+=1
            else:
                neg+=1
            
        pred = 1 if pos>neg else 0
        
        prediction.append(pred)
    return prediction
kfold(df,5)

[[Class      1
Attr_1     0
Attr_2     0
Attr_3     0
Attr_4     0
Attr_5     0
Attr_6     0
Attr_7     0
Attr_8     1
Attr_9     0
Attr_10    0
Attr_11    0
Attr_12    0
Attr_13    1
Attr_14    0
Attr_15    0
Attr_16    0
Attr_17    0
Attr_18    0
Attr_19    0
Attr_20    0
Attr_21    0
Attr_22    1
Name: 131, dtype: int64, 0]]

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().